fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

admin_route:
    resource: "@UserBundle/Resources/config/routing/administrateur.yml"
    prefix:   /admin/

general_route:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:     /

fos_user_registration_confirmed:
    path: /confirmed
    defaults:
        _controller: UserBundle:Default:index
        path: /

fos_user:
     resource: "@FOSUserBundle/Resources/config/routing/all.xml"
